apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: vincentha766
    provider: github
    repository: jx-spring-test
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: vincentha766-jx-spring-test
  namespace: jx
spec:
  httpCloneURL: https://github.com/vincentha766/jx-spring-test.git
  org: vincentha766
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx-spring-test
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/vincentha766/jx-spring-test
